name: Build Image ledger-autoreport
on: [push]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ledger-autoreport
        tags: v1 ${{ github.sha }} latest
        containerfiles: |
          ./provisioning/Containerfile
    - name: Push To ghcr.io
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: v1 ${{ github.sha }} latest
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
   
